version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crud
    ports:
      - "8080:8080"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: kirin
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
